apiVersion: v1
kind: Service
metadata:
  name: minio-api-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
      protocol: TCP
  selector:
    app: minio-api